### PR TITLE
Add test for statistics and fix bug in stats

### PR DESCRIPTION
**Pull request by pgdr**
* Add link to advanced edit (admin panel editor)
* Adds testing for svg output
* Adds testing of loading of pages like `/stats`, `/sau/britanna` and `/sau/britanna/edit`
* Refactored tests, added file `data.py`
* Add favicon

### CODE REVIEW

**Comment by pgdr** [comment]
Tests ... Without them, we really don't know if our code is getting better or worse.

**Comment by pgdr** [comment]
“With tests, we can change the behavior of our code quickly and verifiably. Without them, we really don’t know if our code is getting better or worse.”

Michael Feathers
Working Effectively with Legacy Code

**Comment by pgdr** [comment]
Ready for review

**Review by semafor — APPROVED** [review]
Awesome

**Pull request merged**
